FROM dunglas/frankenphp:latest

# add additional extensions here:
RUN install-php-extensions \
	ctype \
    curl \
    dom \
    exif \
    fileinfo \
    filter \
    hash \
    json \
    libxml \
    mbstring \
    openssl \
    pdo_mysql \
    pcre \
    phar \
    reflection \
    redis \
    session \
    simplexml \
    sodium \
    tokenizer \
    xml \
    xmlreader \
    xmlwriter \
    zip \
