version: '3.9'
services:
  soketi:
    container_name: 'soketi'
    restart: unless-stopped
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    volumes:
      - ./soketi/config.json:/app/bin/config.json:ro
    command: ["pm2", "/app/bin/server.js", "start", "--config=/app/bin/config.json"]
    ports:
      - '${SOKETI_PORT:-6001}:6001'
      - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
    env_file: .env
    environment:
      - DEBUG=1
      - SOKETI_DEBUG='${DEBUG:-1}'
      - DEFAULT_APP_ID='${PUSHER_APP_ID:-some-id}'
      - DEFAULT_APP_KEY='${PUSHER_APP_KEY:-app-key}'
      - DEFAULT_APP_SECRET='${PUSHER_APP_SECRET:-some-app-secret}'
      - PUSHER_HOST='${PUSHER_HOST:-127.0.0.1}'
      - PUSHER_PORT= '${PUSHER_PORT:-6001}'
      - PUSHER_SCHEME='${PUSHER_SCHEME:-http}' # or https
      - METRICS_SERVER_PORT=${METRICS_SERVER_PORT:-9601}
      - DEFAULT_APP_ENABLE_CLIENT_MESSAGES=${DEFAULT_APP_ENABLE_CLIENT_MESSAGES:-false}
    networks:
      - soketi

networks:
  soketi:
    driver: bridge
    name: dev
    external: true
