version: '3.7'
services:
  mysql:
    image: mysql:8
    container_name: 'mysql'
    environment:
      MYSQL_USER: 'moh'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    networks:
      - mysql
    expose:
      - '3306'
    volumes:
      - ./data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  mysql:
    driver: bridge
    name: dev
    external: true
