version: '3.7'

services:
  redis:
    container_name: redis
    image: redis:7.2.3-alpine
    ports:
      - "6379:6379"
    networks:
      - redis
    expose:
      - '6379'
    volumes:
      - ./data:/data
    restart: unless-stopped

volumes:
  redis_data:

networks:
  redis:
    driver: bridge
    name: dev
    external: true
